import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import MyThemeProvider from "@/utils/my-theme-provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Update the theme only if the mode changes
  return (
    <html lang="en">
      <body>
          <AppRouterCacheProvider>
            <MyThemeProvider>{children}</MyThemeProvider>
          </AppRouterCacheProvider>
      </body>
    </html>
  );
}
